//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public System.Guid AnswerId { get; set; }
        public Nullable<System.Guid> QuestionnaireId { get; set; }
        public Nullable<System.Guid> QuestionId { get; set; }
        public Nullable<System.Guid> MultipleChoiceAnswersId { get; set; }
        public Nullable<System.Guid> FreeTextAnswersId { get; set; }
    
        public virtual FreeTextAnswer FreeTextAnswer { get; set; }
        public virtual MultipleChoiceAnswer MultipleChoiceAnswer { get; set; }
        public virtual question question { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
    }
}
